### PR TITLE
Update Notations.v to load Ltac plugin.

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by ejgallego** [comment]
This is backwards incompatible with 8.6, right? Couldn't we ship a dummy `ltac` plugin there?

**Comment by ejgallego** [comment]
Note that this branch is supposed to be merged upstream, so we'd need to create other if we are going to diverge. I have a better plan for HoTT which is to detect the version of Coq and use the proper hack.

**Comment by maximedenes** [comment]
Ok, but what should we do for the immediate future? I'm gonna merge PMP's PR, so it will break travis if we don't merge this one.

**Comment by ejgallego** [comment]
The PR seems to break ssreflect too, so that is a choice I guess, to merge and break the CI, or to fix things first. I see two points:

- My question on why the proof mode is not set by the plugins was not answered.
- Regarding HoTT, if we don't want to break things we can either use the dummy_ltac plugin approach, or else we can improve this patch to detect the Coq version and use the proper file.

IMO, given the current situation the second solution may be more effective as it is likely it is not possible to maintain a compatible stdlib layout hack in for long in HoTT. ssreflect does it properly I think with the `8.5/8.6/trunk` folders.

**Comment by ejgallego** [comment]
Anyways I have added your current patch in the mz-8.7 branch, so you can always point the CI to that and see what happens, cheers.

**Comment by maximedenes** [comment]
Thanks, @ejgallego. I think you can close this PR now that there's a mz-8.7 branch.

**Comment by ejgallego** [comment]
Thanks to you.

**Pull request closed without merging**
