### PR TITLE
Adapt to Coq #1033

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
This will not be compatible with Coq master until coq/coq#1033 is merged.

**Comment by ejgallego** [comment]
Will this be compatible with 8.7 ? If not, I'll branch, or even better, ping the HoTT guys so they make their master 8.7 compatible again.

**Comment by SkySkimmer** [comment]
I don't think it will get backported, so no.

**Comment by ejgallego** [comment]
In fact, I may suggest that we maintain this branch in the HoTT repos itself; @JasonGross, WDYT about this scheme:

- HoTT `master` is compatible with Coq stable.
- HoTT provides a branch `coq-dev` used by Coq master, where we submit pull request, that branch is merged regularly against `master`.

Unfortunately it seems to me that the cost of trying to support a few Coq versions in HoTT is not worth the effort; the universe polymorphic code looks still young and I would dare to guess that it will still see some changes / improvements before it fully stabilizes.

That would mean for HoTT that users willing to support use older Coq versions would have to use older versions of the library.

**Comment by SkySkimmer** [comment]
Had to rebase for arcane reasons.

**Comment by ejgallego** [comment]
I guess you don't want this merged, right? [Coq follows HoTT upstream these days]

**Comment by SkySkimmer** [comment]
Right that was a thing.

**Pull request closed without merging**
