### PR TITLE
Also install ocamlgraph from a package on travis

### PR DESCRIPTION
**Pull request by JasonGross**
This should fix the build failure of coq-dpdgraph, and make travis (finally) happy with this branch.

### CODE REVIEW

**Comment by ejgallego** [comment]
Thanks

**Comment by ejgallego** [comment]
@JasonGross , I've merged this as not to slow down you folks, but the change looks wrong to me, why is camlp5 being reinstalled in a different place than the original one?

**Comment by JasonGross** [comment]
It's not being reinstalled here; if it's already installed, trying to install it again is basically a no-op.  The correct functioning of the code below depends (I believe) on camlp5 being installed via a package, and not via opam, though I'm not 100% sure.  Given this, do you think it's better to remove the `camlp5` installation/installation-check here?  It certainly wouldn't break anything right now to remove it.

**Comment by ejgallego** [comment]
Ok, I think we can live with that, sorry for the noise; I was maybe anticipating a world where ocaml stuff needs to be installed by OPAM, but I think this is fine.

**Comment by JasonGross** [comment]
*nods*  The issue with installing ocaml stuff from opam is that if we install Coq from packages, then the `ocamlfind` path is hardcoded to `/usr/bin/ocamlfind`, so that binary needs to exist and work; a mixed installation is bad news.

**Pull request merged**
